### ISSUE TITLE
LDAP Kerberos auth not supported on Linux

### ISSUE THREAD

**Issue by Dramelac** [franc-pentest/ldeep#34]
Hello,

When using a kerberos authentication from Linux, there is a module missing preventing the authentication.
![image](https://github.com/franc-pentest/ldeep/assets/10145128/a5be5768-129b-48e1-aef1-be582de659d9)

The missing module cant be installed on Linux ?
![image](https://github.com/franc-pentest/ldeep/assets/10145128/c044fd4f-3ecf-4592-9c93-6b652bb532d5)

Thank you for your help

**Comment by Dramelac** [comment]
After some research, the lib `ldap3` need `gssapi` on linux to support kerberos authentication.

**Comment by BastienFaure** [comment]
Is there anything we can add in the `requirements.txt` or is it compile options and/or system packages ?
