### ISSUE TITLE
Unable to bind when DC with ldap signing +channel binding enabled

### ISSUE THREAD

**Issue by enj5oy** [franc-pentest/ldeep#46]
Unable to establish a connection using valid credentials when LDAP signing and channel binding are enabled
![2024-01-24_22-57](https://github.com/franc-pentest/ldeep/assets/143943083/c97bbf73-e3c8-430d-9c5a-8692bebc5cc6)

**Comment by BastienFaure** [comment]
I pushed a small change in the code that should give you more insight about why the bind failed. Can you checkout the latest version locally and give it another shot ? 

Most likely, your LDAP server requires you to bind over LDAPS, give it a try by change your url to `ldaps://192.168.0.4`, it's just that we did not do a smart job by providing a generic error message.

**Comment by enj5oy** [comment]
@BastienFaure 
![2024-01-28_19-41](https://github.com/franc-pentest/ldeep/assets/143943083/07491f62-2b72-41dc-9852-b387ceb94cbd)

**Comment by BastienFaure** [comment]
Check it again, I have added even more verbosity, you should know have an understandable slug on why the bind failed, on top of this verbose error message;

**Comment by enj5oy** [comment]
@BastienFaure same error. I think need patch ldap library like in certipy project (https://github.com/ly4k/Certipy/blob/2780d5361121dd4ec79da3f64cfb1984c4f779c6/certipy/lib/ldap.py#L123)
![2024-01-29_22-13](https://github.com/franc-pentest/ldeep/assets/143943083/156b42f3-4411-431f-b2e9-1a34f50b7865)

**Comment by BastienFaure** [comment]
It says that you have invalid credentials. How are you authenticating exactly ?

**Comment by enj5oy** [comment]
Username + domain + password.
I use correct credentials

**Comment by 3ldidi94** [comment]
Same issue here... I also use correct credentials: domain + username + password and I get the following error message: ```Unable to bind to the LDAP server: invalidCredentials (80090346: LdapErr: DSID-0C0907FB, comment: AcceptSecurityContext error, data 80090346, v4f7c)```

**Comment by BastienFaure** [comment]
are you able to bind to the LDAP server using other tools ? If the server returns `invalidCredentials`, then most likely your credentials are not working guys. I can't really do anything unless I can reproduce.

**Comment by 3ldidi94** [comment]
I was on a hardenned environment that I can't access anymore at the moment but I was 100% confident about my credentials as the same credz were working with other tools. However, the tools from impacket framework were not working either. I will try to create a similar lab environement and conduct some tests using ldeep to reproduce the issue and I will let you know if I am able to reproduc it.

**Comment by BastienFaure** [comment]
What tools did work ? Do you an example of command you did run and completed successfully ?

**Comment by 3ldidi94** [comment]
The credentials works through the SMB protocol or using Powershell on a windows machine, so it is not an issue regarding credentials but maybe the way ldap library manage ldap channel binding

**Comment by enj5oy** [comment]
> are you able to bind to the LDAP server using other tools ? If the server returns `invalidCredentials`, then most likely your credentials are not working guys. I can't really do anything unless I can reproduce.

For reproduce this problem, enable ldaps signing and channel binding in your domain controller.
https://4sysops.com/archives/secure-domain-controllers-with-ldap-channel-binding-and-ldap-signing/

**Comment by 3ldidi94** [comment]
I found this customized ldap3 lib for ldap-channel-binding domain controller (not tested yet, just sharing info that can be useful) : [customized ldap3 lib](https://github.com/ThePirateWhoSmellsOfSunflowers/ldap3/tree/tls_cb_and_seal_for_ntlm)

This library is used in another project that must deal with channel binding: 
[pywerview](https://github.com/the-useless-one/pywerview)

From the Readme of the project, we can find this information about dealing with channel-binding:
The version adds [this PR](https://github.com/cannatag/ldap3/pull/1087) by 
[@ThePirateWhoSmellsOfSunflowers](https://github.com/ThePirateWhoSmellsOfSunflowers) 
and [this one](https://github.com/cannatag/ldap3/pull/1042) by [@CravateRouge](https://github.com/CravateRouge).

**Comment by tiyeuse** [comment]
PR #86 should solve this issue.

**Comment by tiyeuse** [comment]
Closing this issue.
