### ISSUE TITLE
Impossible to modify user password whereas `ForceChangedPassword` is present

### ISSUE THREAD

**Issue by n3rada** [franc-pentest/ldeep#51]
I'm experiencing an issue with the `ldeep` tool when attempting to change user passwords, which works flawlessly with `bloodyAD`. Below are the details of the commands used and the error encountered.

```shell
ldeep ldap -d "dev.com" -s ldap://172.16.172.52 -u "adminweb" -p "aaaadvdfdgdfh" modify_password 'nina' 's3curepassw0rd!'
```
It failed:
```txt
[!] Unable to change nina's password, check privileges or try with ldaps://
```

Whereas with `bloodyAD` it is totally fine:

```shell
bloodyAD --host "172.16.172.52" -d "dev.com" -u "adminweb" -p "aaaadvdfdgdfh"  set password 'nina' 's3curepassw0rd!'
```

Considering the success of the password change using bloodyAD, perhaps ldeep could benefit from integrating a similar method for password modifications. The relevant method in bloodyAD can be found [here](https://github.com/CravateRouge/bloodyAD/blob/aa9a5a8f8c26fe08f7ebb9f9b096f3ba0af1a883/bloodyAD/cli_modules/set.py#L55).

**Comment by BastienFaure** [comment]
@n3rada did you try with LDAPS as suggested ? Most tools will attempt a first connection through LDAPS and thus succeed. But you used an LDAP connection and I would not be surprised that the server requires password changes to be performed over a secured channel.

Maybe we could default to LDAPS (which we don't at the time) but here you specifically requested LDAP.

**Comment by n3rada** [comment]
I tried with LDAPS and it failed too. Did you check the mentioned code block of `bloodyAD` that works?

**Comment by BastienFaure** [comment]
I could but what I would be missing is the configuration of the Active Directory you were working against. I'd like to implement a change but I need to test it against something.

**Comment by n3rada** [comment]
Unfortunately, I didn't control this Active Directory domain. It was a challenge. 🥲

The only thing I know for sure is that it worked with `bloodyAD`. To test, you can try to set the `ForceChangePassword` right on a user (`ExtendedRight` on `User-Force-Change-Password` object type).

**Comment by tiyeuse** [comment]
Few changes have been implemented and this should be an issue anymore. Can you confirm on your side that it works as intended ?

**Comment by n3rada** [comment]
![image](https://github.com/user-attachments/assets/da9ce380-6afa-4cca-bb72-1ed3e265737e)

It works 👀. What did you change in the end? Did you use what the other project does?

**Comment by tiyeuse** [comment]
It was a matter of arguments regarding the function. I did not check what bloodyAD does.

**Comment by n3rada** [comment]
You clearly should. For further improvements!
