### ISSUE TITLE
Feature request: password options that aren't 'put it in the command line'

### ISSUE THREAD

**Issue by dsmith4-godaddy** [franc-pentest/ldeep#52]
I'm not especially keen to have my username _and password_ littered in my shell history, if I can avoid it. I would encourage you to consider adding one (or more) of the following:

* If the -p/--password switch is specified without a value, prompt for the password from the terminal
* Implement a different switch that does the above
* Specify a file or an environment variable that, if set, will be read and its contents used as the password

If there's already an option to do this, a pointer would be appreciated (and it might be useful to update the help text if that's the case).

**Comment by BastienFaure** [comment]
I don't really understand.

```
$ cat credentials.txt
export PASSWORD="yourpassword"
$ source credentials.txt
$ ldeep -u username -p $PASSWORD
```
You can already use that tool without _your password_ littered in your shell history.
