### ISSUE TITLE
Not an Issue just a Feature Request -

### ISSUE THREAD

**Issue by zflemingg1** [franc-pentest/ldeep#7]
Would it be possible to display additional user information in a user summary information such as if they have logged in before and the last time they logged in. I know it's in the verbose output but those are two fields I think people use regularly

**Comment by tiyeuse** [comment]
You can do it super easily with `jq` as a workaround:
```
$ ldeep ldap -d CORP -s CORP.LOCAL -u bob -p password users -v |jq -r '.[]|[.sAMAccountName,.lastLogonTimestamp]| join(",")'
admin,2022-04-21T15:26:09.897070+00:00
bob,2022-04-22T10:09:48.103016+00:00
[...]
```

**Comment by BastienFaure** [comment]
Thanks @tiyeuse, closing this issue.
