### ISSUE TITLE
Module no module named tqdm found

### ISSUE THREAD

**Issue by nithish1one** [franc-pentest/ldeep#98]
Any solution for tqdm error??
It is showing no module found

**Comment by tiyeuse** [comment]
Hi @nithish1one,

Do you have more details regarding your operating system and your installation procedure ? If you have errors, feel free to paste them.
The `tqdm` dependency is specified in the `pyproject.toml` file. If you do something like `pip install .` in the folder the library should be present.

**Comment by BastienFaure** [comment]
@nithish1one closing unless you want to reopen with proper reproduction steps. And please try to be nice, we support this tool on our free time.
